quote/config/routes.rb
Rails.application.routes.draw do
  resources :v_quotes
  root "v_quotes#index"

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
end

quote/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

quote/app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

quote/app/models/quote.rb
class Quote < ApplicationRecord
end

quote/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true, format: { 
    with: /\A[^@\s]+@[^@\s]+\z/, 
    message: 'Invalid email' 
  }
end

quote/app/models/v_quote.rb
class VQuote < ApplicationRecord
  belongs_to :user
end

quote/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You mush be signed in" if Current.user.nil?
  end
end

quote/app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in!
  
  def edit; end
  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password Updated"
    else
      render :edit
    end
  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)

quote/app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!
  
  def edit; end
  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password Updated"
    else
      render :edit
    end
  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

quote/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
  end
end

quote/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

quote/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end
  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in"
    else 
      flash.now[:alert] = "invalid email & password"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end
end

quote/app/controllers/v_quotes_controller.rb
class VQuotesController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_v_quote, only: %i[ show edit update destroy ]
  before_action :require_quote_owner, only: [:edit, :update, :destroy]

  # GET /v_quotes or /v_quotes.json
  def index
    @v_quotes = VQuote.all
  end

  # GET /v_quotes/1 or /v_quotes/1.json
  def show
  end

  # GET /v_quotes/new
  def new
    @v_quote = VQuote.new
  end

  # GET /v_quotes/1/edit
  def edit
  end

  # POST /v_quotes or /v_quotes.json
  def create
    @v_quote = VQuote.new(v_quote_params.merge(user_id: Current.user.id))

    respond_to do |format|
      if @v_quote.save
        format.html { redirect_to v_quote_url(@v_quote), notice: "V quote was successfully created." }
        format.json { render :show, status: :created, location: @v_quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @v_quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /v_quotes/1 or /v_quotes/1.json
  def update
    respond_to do |format|
      if @v_quote.update(v_quote_params)
        format.html { redirect_to v_quote_url(@v_quote), notice: "V quote was successfully updated." }
        format.json { render :show, status: :ok, location: @v_quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @v_quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /v_quotes/1 or /v_quotes/1.json
  def destroy
    @v_quote.destroy

    respond_to do |format|
      format.html { redirect_to v_quotes_url, notice: "V quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_v_quote
      @v_quote = VQuote.find(params[:id])
    end

    def require_quote_owner
      @v_quote = VQuote.find(params[:id])
      unless Current.user.id == @v_quote.user.id
        redirect_to root_path, notice: 'Unauthorized'
      end
    end

    # Only allow a list of trusted parameters through.
    def v_quote_params
      params.require(:v_quote).permit(:quote, :authur)
    end
end

quote/app/helpers/application_helper.rb
module ApplicationHelper
end

quote/app/helpers/quotes_helper.rb
module QuotesHelper
end

quote/app/helpers/v_quotes_helper.rb
module VQuotesHelper
  def owner(v_quote)
    v_quote.user.id == Current.user.id
  end
end

quote/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

quote/app/views/quotes/index.html.erb
<h1>Quotes#index</h1>
<p>Find me in app/views/quotes/index.html.erb</p>

quote/app/views/v_quotes/_form.html.erb
<%= form_with(model: v_quote) do |form| %>
  <% if v_quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(v_quote.errors.count, "error") %> prohibited this v_quote from being saved:</h2>

      <ul>
        <% v_quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quote, style: "display: block" %>
    <%= form.text_area :quote %>
  </div>

  <div>
    <%= form.label :authur, style: "display: block" %>
    <%= form.text_area :authur %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

quote/app/views/v_quotes/_v_quote.html.erb
<div id="<%= dom_id v_quote %>">
  <p>
    <strong>Quote:</strong>
    <%= v_quote.quote %> - <%= v_quote.authur %>
    <br>Published by: <%= v_quote.user.email %>
  </p>
</div>

quote/app/views/v_quotes/edit.html.erb
<h1>Editing v quote</h1>

<%= render "form", v_quote: @v_quote %>

<br>

<div>
  <%= link_to "Show this v quote", @v_quote %> |
  <%= link_to "Back to v quotes", v_quotes_path %>
</div>

quote/app/views/v_quotes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quotes</h1>

<div id="v_quotes">
  <% @v_quotes.each do |v_quote| %>
    <%= render v_quote %>
    <% if owner(v_quote) %>
      <%= link_to "Edit", edit_v_quote_path(v_quote) %>
      <%= button_to "Delete", v_quote, method: :delete %>
    <% end %>
  <% end %>
</div>
<br><br>

<%= link_to "New v quote", new_v_quote_path %>

<br><br>
<% if Current.user %>
  Logged in as: <%= Current.user.email %><br>
  <%= link_to 'Edit Password', edit_password_path %>
  <%= button_to 'Logout', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Sign Up', sign_up_path %> or <%= link_to 'Login', sign_in_path %>
<% end %>

quote/app/views/v_quotes/new.html.erb
<h1>New v quote</h1>

<%= render "form", v_quote: @v_quote %>

<br>

<div>
  <%= link_to "Back to v quotes", v_quotes_path %>
</div>

quote/app/views/v_quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @v_quote %>

<div>
  <%= link_to "Edit this v quote", edit_v_quote_path(@v_quote) %> |
  <%= link_to "Back to v quotes", v_quotes_path %>

  <%= button_to "Destroy this v quote", @v_quote, method: :delete %>
</div>