config/routes.rb
Rails.application.routes.draw do
  # get 'timelines/index'
  # get 'timelines/show'
  devise_for :users
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  #   get '/users/sign_up' => 'devise/registrations/new#post'
  #   get '/users/login' => 'devise/sessions/new#post'
  # end
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  # Registering the Paths of the TimelinesController
  authenticate :user do
    resources :timelines,
              only: %i[index show],
              # let’s tell the router to call the identifier as a username instead of an ID
              params: :username
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/member/_member.html.erb
<nav class="topnav">
  <div class="flex items-center flex-shrink-0">
    <%= link_to timelines_path do %>
      <h1>tandibi</h1>
    <% end %>
  </div>
  <div class="block flex-grow flex items-center w-auto">
    <div class="text-sm flex-grow">
      <%= link_to timelines_path,
        class: "linked-icon #{"active" if on_bunch?}" do %>
      <% end %>
      <%= link_to timeline_path(current_user),
        class: "linked-icon #{"active" if on_current_user?}" do %>
      <% end %>
    </div>
    <div>
      <%= link_to destroy_user_session_path,
        class: "linked-icon sign-out",
        method: :delete do %>
      <% end %>
    </div>
  </div>
</nav>